name: csr-v2
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - comm=0.2.2=pyhd8ed1ab_1
  - cudatoolkit=11.8.0=h4ba93d1_13
  - debugpy=1.8.15=py311hc665b79_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - faiss-gpu=1.9.0=h418687c_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=9.4.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h1423503_5
  - libblas=3.9.0=35_h59b9bed_openblas
  - libcblas=3.9.0=35_he106b2a_openblas
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.0=h5888daf_0
  - libfaiss=1.9.0=cuda118hf323835_0_cuda
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libgomp=15.1.0=h767d61c_3
  - liblapack=3.9.0=35_h7ac8fdf_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.50.2=h6cd9bfd_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=15.1.0=h4852527_3
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.2=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1.1=pyh8b19718_0
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py311h9ecbd09_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.13=h9e4cc4f_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=8_cp311
  - pyzmq=27.0.0=py311h7deb3e3_0
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sysroot_linux-64=2.34=h087de78_2
  - tk=8.6.13=noxft_hd72426e_102
  - tornado=6.5.1=py311h9ecbd09_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.9.0
      - addict==2.4.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.3.2
      - airportsdata==20250622
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - annotated-types==0.7.0
      - anyio==4.9.0
      - assertpy==1.1
      - astor==0.8.1
      - attrdict==2.0.1
      - attrs==25.3.0
      - binpacking==1.5.2
      - bitsandbytes==0.46.1
      - blake3==1.0.5
      - brotli==1.1.0
      - cachetools==6.1.0
      - certifi==2025.6.15
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cloudpickle==3.1.1
      - compressed-tensors==0.10.2
      - contourpy==1.3.2
      - cpm-kernels==1.0.11
      - crcmod==1.7
      - cryptography==45.0.5
      - cupy-cuda12x==13.4.1
      - cycler==0.12.1
      - dacite==1.9.2
      - datasets==3.3.2
      - deepspeed==0.17.2
      - deprecated==1.2.18
      - depyf==0.18.0
      - dill==0.3.6
      - discover==0.4.0
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.7.0
      - einops==0.8.1
      - email-validator==2.2.0
      - et-xmlfile==2.0.0
      - eval-type-backport==0.2.2
      - evaluate==0.4.0
      - faiss-gpu-cu12==1.12.0
      - fastapi==0.115.14
      - fastapi-cli==0.0.7
      - fastargs==1.2.0
      - fastrlock==0.8.3
      - ffcv==1.0.2
      - ffmpy==0.6.0
      - filelock==3.18.0
      - flash-attn==2.8.2
      - fonttools==4.58.5
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - future==1.0.0
      - gguf==0.17.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - googleapis-common-protos==1.70.0
      - gradio==5.36.2
      - gradio-client==1.10.4
      - groovy==0.1.2
      - grpcio==1.73.1
      - h11==0.16.0
      - hf-xet==1.1.5
      - hjson==3.1.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - idna==3.10
      - importlib-metadata==8.0.0
      - inflate64==1.0.3
      - interegular==0.3.3
      - jieba==0.42.1
      - jinja2==3.1.6
      - jiter==0.10.0
      - jmespath==0.10.0
      - joblib==1.5.1
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.8
      - lark==1.2.2
      - lightning-utilities==0.15.2
      - llguidance==0.7.30
      - llvmlite==0.44.0
      - lm-format-enforcer==0.10.11
      - loralib==0.1.2
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - mistral-common==1.6.2
      - modelscope==1.28.0
      - mpmath==1.3.0
      - ms-swift==3.7.0
      - msgpack==1.1.1
      - msgspec==0.19.0
      - mteb==1.38.39
      - multidict==6.6.3
      - multiprocess==0.70.14
      - multivolumefile==0.2.3
      - networkx==3.5
      - ninja==1.11.1.4
      - nltk==3.9.1
      - numba==0.61.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - openai==1.90.0
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.11.0.86
      - openpyxl==3.1.5
      - opentelemetry-api==1.35.0
      - opentelemetry-exporter-otlp==1.26.0
      - opentelemetry-exporter-otlp-proto-common==1.26.0
      - opentelemetry-exporter-otlp-proto-grpc==1.26.0
      - opentelemetry-exporter-otlp-proto-http==1.26.0
      - opentelemetry-proto==1.26.0
      - opentelemetry-sdk==1.26.0
      - opentelemetry-semantic-conventions==0.56b0
      - opentelemetry-semantic-conventions-ai==0.4.9
      - orjson==3.10.18
      - oss2==2.19.1
      - outlines==0.1.11
      - outlines-core==0.1.26
      - pandas==2.3.0
      - partial-json-parser==0.2.1.1.post6
      - peft==0.15.2
      - pillow==11.3.0
      - polars==1.31.0
      - prometheus-client==0.22.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.3.2
      - protobuf==4.25.8
      - py-cpuinfo==9.0.0
      - py7zr==1.0.0
      - pyarrow==20.0.0
      - pybase64==1.4.1
      - pybcj==1.0.6
      - pycountry==24.6.1
      - pycparser==2.22
      - pycryptodome==3.23.0
      - pycryptodomex==3.23.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pyparsing==3.2.3
      - pyppmd==1.2.0
      - python-dotenv==1.1.1
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pytorch-pfn-extras==0.8.4
      - pytrec-eval-terrier==0.5.7
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzstd==0.17.0
      - ray==2.47.1
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.4
      - responses==0.18.0
      - rich==14.0.0
      - rich-toolkit==0.14.8
      - rouge==1.0.1
      - rouge-score==0.1.2
      - rpds-py==0.25.1
      - ruff==0.12.3
      - safehttpx==0.1.6
      - safetensors==0.5.3
      - scikit-learn==1.7.0
      - scipy==1.16.0
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentence-transformers==5.0.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.32.0
      - shellingham==1.5.4
      - simplejson==3.20.1
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - starlette==0.46.2
      - sympy==1.14.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - terminaltables==3.1.10
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - timm==1.0.16
      - tokenizers==0.21.2
      - tomlkit==0.13.3
      - torch==2.7.0
      - torchaudio==2.7.0
      - torchmetrics==1.8.2
      - torchvision==0.22.0
      - tqdm==4.67.1
      - transformers==4.55.0
      - transformers-stream-generator==0.0.5
      - triton==3.3.0
      - trl==0.19.1
      - typer==0.16.0
      - typing-extensions==4.14.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.35.0
      - uvloop==0.21.0
      - vllm==0.9.2
      - wandb==0.21.0
      - watchfiles==1.1.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xformers==0.0.30
      - xgrammar==0.1.19
      - xxhash==3.5.0
      - yarl==1.20.1
      - zstandard==0.23.0
prefix: /opt/conda/envs/csr-v2
